groups:
    - name: targets
      rules:
          - alert: server_down
            expr: up == 0
            for: 30s
            labels:
                severity: critical
            annotations:
                summary: "Server non-operational"
                description: "Server {{ $labels.instance }} is down."
    - name: host
      rules:
          - alert: high_cpu_load
            expr: sum(rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode="user"})) < 15
            for: 30s
            labels:
                severity: warning
            annotations:
                summary: "Server under high load"
                description: "Server is under high load, the free CPU is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

          - alert: high_memory_load
            expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
            for: 30s
            labels:
                severity: warning
            annotations:
                summary: "Server memory is almost full"
                description: "Server memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

          - alert: high_storage_load
            expr: (node_filesystem_size_bytes{fstype="xfs"} - node_filesystem_free_bytes{fstype="xfs"}) / node_filesystem_size_bytes{fstype="xfs"}  * 100 > 85
            for: 30s
            labels:
                severity: warning
            annotations:
                summary: "Server storage is almost full"
                description: "Server storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."