global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
    external_labels:
        monitor: monitor
rule_files:
    - alert_rules.yml
alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets:
                    - alertmanager:9093
scrape_configs:

    - job_name: prometheus
      scrape_interval: 10s
      static_configs:
          - targets:
                - localhost:9090
            labels:
                instance: monitoring

    - job_name: cadvisor-local
      scrape_interval: 10s
      static_configs:
          - targets:
                - cadvisor:8080
            labels:
                instance: monitoring

    - job_name: node-exporter-local
      scrape_interval: 10s
      static_configs:
          - targets:
                - node-exporter:9100
            labels:
                instance: monitoring

    - job_name: 'heimdall'
      digitalocean_sd_configs:
        - port: 26660
        - authorization:
            credentials: "${DO_AUTH_TOKEN}"
      relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_digitalocean_tags]
        regex: ".*,monitoring,.*"
        action: keep
      - source_labels: [__meta_digitalocean_public_ipv4]
        target_label: __address__
        replacement: "[$1]:26660"

    # - job_name: 'bor'
    #   scrape_interval: 10s
    #   scrape_timeout: 10s
    #   metrics_path: /debug/metrics/prometheus
    #   scheme: http
    #   static_configs:
    #   - targets: ['127.0.0.1:7071']